<#
.SYNOPSIS
  Run several Claude Desktop accounts side by side on one Windows user.

.DESCRIPTION
  Creates an isolated Claude Desktop instance: its own Electron user-data dir
  (login, settings, MCP servers, sessions) and its own Claude Code config dir,
  plus Desktop and Start-menu shortcuts. Your default Claude install is never touched.

  Not an official Anthropic feature: it relies on Electron's standard
  --user-data-dir switch, which a future Claude update could stop honouring.

.EXAMPLE
  .\Install-ClaudeInstance.ps1                     # asks for a name
  .\Install-ClaudeInstance.ps1 -Name Work
  .\Install-ClaudeInstance.ps1 -Name Work -Uninstall            # remove shortcuts, keep data
  .\Install-ClaudeInstance.ps1 -Name Work -Uninstall -RemoveData
#>
param(
    [string]$Name,
    [switch]$Uninstall,
    [switch]$RemoveData,
    [switch]$NoLaunch
)

$ErrorActionPreference = 'Stop'
$root      = Join-Path $env:LOCALAPPDATA 'ClaudeInstances'
$launcher  = Join-Path $root 'Launch-Claude.ps1'
$desktop   = [Environment]::GetFolderPath('Desktop')
$startMenu = Join-Path ([Environment]::GetFolderPath('Programs')) 'Claude Instances'

if (-not $Name) {
    $Name = Read-Host 'Instance name (letters, digits, - or _), e.g. Account2'
}
if ($Name -notmatch '^[A-Za-z0-9_-]{1,40}$') {
    throw "Invalid name '$Name'. Use letters, digits, - or _ only."
}

$dataDir  = Join-Path $root $Name
$lnkName  = "Claude - $Name.lnk"
$lnkPaths = @((Join-Path $desktop $lnkName), (Join-Path $startMenu $lnkName))

# ---------- uninstall ----------
if ($Uninstall) {
    $lnkPaths | Where-Object { Test-Path $_ } | ForEach-Object { Remove-Item $_; "Removed shortcut: $_" }
    if ($RemoveData -and (Test-Path $dataDir)) {
        $running = Get-CimInstance Win32_Process -Filter "Name='claude.exe'" |
            Where-Object { $_.CommandLine -like "*$dataDir*" }
        if ($running) { throw "Instance '$Name' is running. Close its window first." }
        Remove-Item $dataDir -Recurse -Force
        "Removed data: $dataDir"
    } elseif (Test-Path $dataDir) {
        "Data kept at: $dataDir  (add -RemoveData to delete it)"
    }
    return
}

# ---------- find Claude ----------
function Get-ClaudeExe {
    $pkg = Get-AppxPackage -Name Claude -ErrorAction SilentlyContinue |
        Sort-Object Version -Descending | Select-Object -First 1
    if ($pkg) { return Join-Path $pkg.InstallLocation 'app\claude.exe' }
    $legacy = Join-Path $env:LOCALAPPDATA 'AnthropicClaude\claude.exe'   # older non-MSIX installer
    if (Test-Path $legacy) { return $legacy }
    return $null
}
$exe = Get-ClaudeExe
if (-not $exe) { throw 'Claude Desktop is not installed. Get it from https://claude.ai/download first.' }

# ---------- launcher (shared by every instance) ----------
New-Item -ItemType Directory -Force $root, $dataDir, $startMenu | Out-Null
@'
# Generated by Install-ClaudeInstance.ps1 - launches one isolated Claude Desktop instance.
param([Parameter(Mandatory)][string]$Name)
$dataDir = Join-Path (Join-Path $env:LOCALAPPDATA 'ClaudeInstances') $Name
$codeDir = Join-Path $dataDir 'claude-code'
New-Item -ItemType Directory -Force $dataDir, $codeDir | Out-Null

# Resolved on every launch: the MSIX path contains the version and changes on update.
$pkg = Get-AppxPackage -Name Claude -ErrorAction SilentlyContinue | Sort-Object Version -Descending | Select-Object -First 1
$exe = if ($pkg) { Join-Path $pkg.InstallLocation 'app\claude.exe' } else { Join-Path $env:LOCALAPPDATA 'AnthropicClaude\claude.exe' }
if (-not (Test-Path $exe)) { exit 1 }

$env:CLAUDE_CONFIG_DIR = $codeDir
Start-Process -FilePath $exe -ArgumentList "--user-data-dir=`"$dataDir`""
'@ | Set-Content -Path $launcher -Encoding UTF8

# ---------- shortcuts ----------
$ws = New-Object -ComObject WScript.Shell
foreach ($p in $lnkPaths) {
    $l = $ws.CreateShortcut($p)
    $l.TargetPath   = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
    $l.Arguments    = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$launcher`" -Name $Name"
    $l.IconLocation = "$exe,0"
    $l.WindowStyle  = 7
    $l.Description  = "Claude Desktop - isolated instance '$Name'"
    $l.Save()
}

""
"Instance '$Name' is ready."
"  Data:      $dataDir"
"  Shortcuts: Desktop and Start menu -> 'Claude - $Name'"
""
"Tip: sign in to the new window with an email code. A browser login that"
"returns through a claude:// link is delivered to your default Claude window."

if (-not $NoLaunch) {
    & powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File $launcher -Name $Name
}
